// GENERATED by tools/gen_param_tables.py - edit the generator, not this file.
//
// The Additive instrument's parameters, in the order its node reads them. The first
// block is iteration one's patch, named as the v1 shim names it (phase_4.md §4.3);
// the harmonics extend v1's sixteen to 64, each with a level, a detune in cents and
// a start phase. The three curve blocks are not parameters of their own: they carry
// the `curve=` of env.attack, env.decay and env.release to a node that only sees
// floats (ParamDescriptor.h, CurvePart).
#pragma once

#include <array>
#include <cstdint>

#include "engine/project/ParamDescriptor.h"

namespace adx::instruments {

inline constexpr std::uint32_t kAdditiveHarmonics = 64;

enum class AdditiveParam : std::uint32_t {
    EnvAttack,
    EnvDecay,
    EnvSustain,
    EnvRelease,
    Drive,
    FilterCutoff,
    FilterLfoRate,
    FilterLfoDepth,
    SubLevel,
    SubWave,
    SubDropSemitones,
    SubDropMs,
    NoiseLevel,
    NoiseType,
    OscWave,
    OscUnison,
    OscDetuneCents,
    OscPulseWidth,
    ResfilterType,
    ResfilterCutoff,
    ResfilterResonance,
    ResfilterEnvAmount,
    ResfilterKeyTrack,
    FilterEnvAttack,
    FilterEnvDecay,
    FilterEnvSustain,
    FilterEnvRelease,
    FormantVowelA,
    FormantVowelB,
    FormantMorph,
    FormantAmount,
    VibratoRate,
    VibratoDepthCents,
    VibratoDelayMs,
    GlideMs,
    HarmonicsSeries,
    MorphTarget,
    MorphAmount,
    EnvAttackCurveKind,
    EnvAttackCurveTension,
    EnvAttackCurveC1x,
    EnvAttackCurveC1y,
    EnvAttackCurveC2x,
    EnvAttackCurveC2y,
    EnvDecayCurveKind,
    EnvDecayCurveTension,
    EnvDecayCurveC1x,
    EnvDecayCurveC1y,
    EnvDecayCurveC2x,
    EnvDecayCurveC2y,
    EnvReleaseCurveKind,
    EnvReleaseCurveTension,
    EnvReleaseCurveC1x,
    EnvReleaseCurveC1y,
    EnvReleaseCurveC2x,
    EnvReleaseCurveC2y,
    Harmonic1,
    HarmonicDetune1 = Harmonic1 + kAdditiveHarmonics,
    HarmonicPhase1 = HarmonicDetune1 + kAdditiveHarmonics,
    Count = HarmonicPhase1 + kAdditiveHarmonics,
};

/// One descriptor per AdditiveParam, in enum order (AdditiveParams.cpp).
extern const std::array<project::ParamDescriptor, static_cast<std::size_t>(AdditiveParam::Count)>
    kAdditiveParams;

} // namespace adx::instruments
