#include "engine/instruments/fm/FmParams.h"

namespace adx::instruments {

// NOLINTBEGIN(modernize-use-designated-initializers) - a table reads as a table.
const std::array<project::ParamDescriptor, kFmParamCount> kFmParams =
    std::to_array<project::ParamDescriptor>({
        {"algorithm", 1.0F, 32.0F, 1.0F, project::Unit::Count, project::ScaleKind::Stepped,
         project::RateClass::Block, project::CurvePart::None},
        {"feedback", 0.0F, 1.0F, 0.0F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"level", -48.0F, 12.0F, -6.0F, project::Unit::Decibels, project::ScaleKind::Linear,
         project::RateClass::Sample, project::CurvePart::None},
        {"glide", 0.0F, 5.0F, 0.0F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.ratio", 0.5F, 32.0F, 1.0F, project::Unit::Ratio, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.fixed", 0.0F, 1.0F, 0.0F, project::Unit::Boolean, project::ScaleKind::Stepped,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.freq", 1.0F, 20000.0F, 440.0F, project::Unit::Hertz, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.detune", -100.0F, 100.0F, 0.0F, project::Unit::Cents, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.level", 0.0F, 1.0F, 1.0F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.attack", 0.0F, 10.0F, 0.002F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.decay", 0.0F, 10.0F, 0.6F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.sustain", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.release", 0.0F, 10.0F, 0.3F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op1.velocity", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.ratio", 0.5F, 32.0F, 1.0F, project::Unit::Ratio, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.fixed", 0.0F, 1.0F, 0.0F, project::Unit::Boolean, project::ScaleKind::Stepped,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.freq", 1.0F, 20000.0F, 440.0F, project::Unit::Hertz, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.detune", -100.0F, 100.0F, 0.0F, project::Unit::Cents, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.level", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.attack", 0.0F, 10.0F, 0.002F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.decay", 0.0F, 10.0F, 0.6F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.sustain", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.release", 0.0F, 10.0F, 0.3F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op2.velocity", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.ratio", 0.5F, 32.0F, 1.0F, project::Unit::Ratio, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.fixed", 0.0F, 1.0F, 0.0F, project::Unit::Boolean, project::ScaleKind::Stepped,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.freq", 1.0F, 20000.0F, 440.0F, project::Unit::Hertz, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.detune", -100.0F, 100.0F, 0.0F, project::Unit::Cents, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.level", 0.0F, 1.0F, 0.0F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.attack", 0.0F, 10.0F, 0.002F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.decay", 0.0F, 10.0F, 0.6F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.sustain", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.release", 0.0F, 10.0F, 0.3F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op3.velocity", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.ratio", 0.5F, 32.0F, 1.0F, project::Unit::Ratio, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.fixed", 0.0F, 1.0F, 0.0F, project::Unit::Boolean, project::ScaleKind::Stepped,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.freq", 1.0F, 20000.0F, 440.0F, project::Unit::Hertz, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.detune", -100.0F, 100.0F, 0.0F, project::Unit::Cents, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.level", 0.0F, 1.0F, 0.0F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.attack", 0.0F, 10.0F, 0.002F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.decay", 0.0F, 10.0F, 0.6F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.sustain", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.release", 0.0F, 10.0F, 0.3F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op4.velocity", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.ratio", 0.5F, 32.0F, 1.0F, project::Unit::Ratio, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.fixed", 0.0F, 1.0F, 0.0F, project::Unit::Boolean, project::ScaleKind::Stepped,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.freq", 1.0F, 20000.0F, 440.0F, project::Unit::Hertz, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.detune", -100.0F, 100.0F, 0.0F, project::Unit::Cents, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.level", 0.0F, 1.0F, 0.0F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.attack", 0.0F, 10.0F, 0.002F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.decay", 0.0F, 10.0F, 0.6F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.sustain", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.release", 0.0F, 10.0F, 0.3F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op5.velocity", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.ratio", 0.5F, 32.0F, 1.0F, project::Unit::Ratio, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.fixed", 0.0F, 1.0F, 0.0F, project::Unit::Boolean, project::ScaleKind::Stepped,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.freq", 1.0F, 20000.0F, 440.0F, project::Unit::Hertz, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.detune", -100.0F, 100.0F, 0.0F, project::Unit::Cents, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.level", 0.0F, 1.0F, 0.0F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.attack", 0.0F, 10.0F, 0.002F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.decay", 0.0F, 10.0F, 0.6F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.sustain", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.release", 0.0F, 10.0F, 0.3F, project::Unit::Seconds, project::ScaleKind::Logarithmic,
         project::RateClass::Block, project::CurvePart::None},
        {"op6.velocity", 0.0F, 1.0F, 0.5F, project::Unit::Normalized, project::ScaleKind::Linear,
         project::RateClass::Block, project::CurvePart::None},
    });
// NOLINTEND(modernize-use-designated-initializers)

} // namespace adx::instruments
