// adx-thread: main
//
// Text in the encodings voicebanks use: Shift-JIS (cp932) and UTF-8, detected.
//
// UTAU banks' oto.ini, character.txt and readme.txt are very commonly Shift-JIS - Kasane
// Teto's are (phase_4.md §4.13). Decoding is a table lookup (ShiftJisTable.cpp,
// generated by tools/gen_sjis_table.py) rather than an OS call, so a bank reads the
// same everywhere. The user's bytes are never rewritten: callers keep the original and
// decode a copy.
#pragma once

#include <cstdint>
#include <span>
#include <string>
#include <string_view>

namespace adx::format {

enum class TextEncoding : std::uint8_t { Utf8, ShiftJis };

/// The table: (code << 16) | UTF-16 unit, sorted by code. Generated.
[[nodiscard]] std::span<const std::uint32_t> shiftJisTable() noexcept;

/// True when `bytes` is well-formed UTF-8 (a BOM allowed).
[[nodiscard]] bool isUtf8(std::string_view bytes) noexcept;

/// UTF-8 when it is well-formed UTF-8, else Shift-JIS: plain ASCII is both, and reads
/// the same either way.
[[nodiscard]] TextEncoding detectEncoding(std::string_view bytes) noexcept;

/// Shift-JIS (cp932) bytes to UTF-8. A byte sequence that is not cp932 becomes U+FFFD.
[[nodiscard]] std::string shiftJisToUtf8(std::string_view bytes);

/// `bytes` as UTF-8, whatever detectEncoding says they are; a UTF-8 BOM is dropped.
[[nodiscard]] std::string toUtf8(std::string_view bytes);

} // namespace adx::format
