"""Generate engine/format/text/ShiftJisTable.cpp: the cp932 double-byte table.

UTAU voicebanks write oto.ini, character.txt and readme.txt in Shift-JIS - in practice
Windows code page 932, Shift-JIS plus NEC and IBM extensions, which is what Python
calls cp932 (phase_4.md §4.13). The engine decodes it with this table rather than the
OS, so a bank reads the same on every platform.

    python tools/gen_sjis_table.py
"""

from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "engine" / "format" / "text" / "ShiftJisTable.cpp"


def pairs() -> list[tuple[int, int]]:
    found: list[tuple[int, int]] = []
    leads = list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD))
    trails = list(range(0x40, 0x7F)) + list(range(0x80, 0xFD))
    for lead in leads:
        for trail in trails:
            try:
                text = bytes([lead, trail]).decode("cp932")
            except UnicodeDecodeError:
                continue
            if len(text) == 1 and ord(text) <= 0xFFFF:
                found.append(((lead << 8) | trail, ord(text)))
    return found


def main() -> None:
    table = pairs()
    lines = [
        "// GENERATED by tools/gen_sjis_table.py - edit the generator, not this file.",
        "//",
        "// cp932 double-byte codes to UTF-16 code units, sorted by code: (code << 16) | unit.",
        '#include "engine/format/text/ShiftJis.h"',
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace adx::format {",
        "",
        f"const std::array<std::uint32_t, {len(table)}> kShiftJisTable{{{{",
    ]
    row: list[str] = []
    for code, unit in table:
        row.append(f"0x{(code << 16) | unit:08X}U")
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines += [
        "}};",
        "",
        "std::span<const std::uint32_t> shiftJisTable() noexcept {",
        "    return kShiftJisTable;",
        "}",
        "",
        "} // namespace adx::format",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{OUT}: {len(table)} codes")


if __name__ == "__main__":
    main()
