// A synthetic UTAU voicebank, generated on first use into the temp directory
// (phase_4.md §4.13: "a tiny synthetic voicebank generated by script mirroring Teto's
// structure - no real banks in the repo").
//
// It reproduces the quirks the parser and resolver must survive, measured on Kasane
// Teto: a tree of sub-banks (単独音 CV, 連続音 VCV); Shift-JIS oto.ini and
// character.txt; Japanese WAV names; several aliases per WAV (`あ`, `- あ`, `* あ`);
// VCV aliases `<vowel> <kana>`; negative cutoffs; fractional timings; and a FREQ0003
// .frq beside every WAV. The voice is a glottal pulse train at D#4 (311.13 Hz) through
// each vowel's formants, with a noise burst for か's consonant.
#pragma once

#include <filesystem>

namespace adx::tests {

/// The bank's root folder, created once per process.
[[nodiscard]] const std::filesystem::path& syntheticVoicebank();

/// The synthetic voice's pitch, D#4.
inline constexpr double kSyntheticF0 = 311.127;

} // namespace adx::tests
